name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_please_info: ${{ toJSON(steps.release.outputs) }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

  release-info:
    runs-on: ubuntu-latest
    needs:
      - release-please
    env:
      release_please_info: ${{ needs.release-please.outputs.release_please_info }}
      output: ${{ toJSON(needs.release-please.outputs) }}
      paths_released: ${{ needs.release-please.outputs.paths_released }}
    steps:
      - name: Show Release Please Results
        run: |
          echo "PATHS: $paths_released"
          echo "$release_please_info"
          echo OUTPUT
          echo "$output"
      - name: Release
        if: ${{ needs.release-please.outputs.release_created }}
        run: echo RELEASE

      - name: No Release
        if: ${{ !needs.release-please.outputs.release_created }}
        run: echo Not Released

  publish:
    needs:
      - release-please
    uses: ./.github/workflows/publish.yml
    with:
      ref: main
      paths_released: ${{ needs.release-please.outputs.paths_released }}
    secrets:
      VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
    if: ${{ needs.release-please.outputs.release_created }}
