name: " ðŸ”— Update Extension Lists"

on:
  push:
    branches:
      - main

  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  update-extension-lists:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: "update-extension-lists"
    steps:
      - name: Start
        run: |
          echo "${{ toJson(github.event.inputs) }}"
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install
        run: npm install

      - name: Update Workspace
        run: |
          npm run gen:readme

      - name: Update Release Please Packages
        run: |
          npm run gen:release-please

      - name: PR Body
        id: pr-body
        uses: streetsidesoftware/actions/public/pr-body@v1
        with:
          title: "ci: Update README / Extensions List"
          message: |
            Update README / Extensions List with any new extensions that have been added to the marketplace.
          path: >-
            README.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "ci: Update README / Extensions List"
          branch: ${{ env.NEW_BRANCH }}
          base: main
          title: "ci: Update README / Extensions List"
          body: ${{ steps.pr-body.outputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
